### ISSUE TITLE
Gesture functionality - feature

### ISSUE THREAD

**Issue by chadgainor** [Saakshaat/dequarantine#1]
Swipe events left/right to dismiss/add to calendar?

**Comment by Saakshaat** [comment]
@Germain-L are there any libraries in Flutter that could facilitate this or would you have to make everything from scratch?

**Comment by Saakshaat** [comment]
@chadgainor @Adilkhan510 does React have any libraries for this?

**Comment by Germain-L** [comment]
> @Germain-L are there any libraries in Flutter that could facilitate this or would you have to make everything from scratch?

depends on the complexity really, what exactly are you thinking of?

**Comment by Saakshaat** [comment]
> > @Germain-L are there any libraries in Flutter that could facilitate this or would you have to make everything from scratch?
> 
> depends on the complexity really, what exactly are you thinking of?

A simple gesture based feature for mobile platforms wherein our user swipes in a certain direction to trigger a certain action.

Here's something I found specific to Flutter 
`https://medium.com/@info_67212/flutter-swipe-your-widget-for-more-action-items-2b85866ca238`
