### ISSUE TITLE
Google Calendar Integration for adding Events to User's GCal

### ISSUE THREAD

**Issue by Saakshaat** [Saakshaat/dequarantine#34]
## Background 
We have a feature in the backend for marking an event attended, when the user sends a GET request to `/baseapi/events/markAttended/:eventId`. This simply adds the user's userName to the event object's participating field and adds the eventId of the event to the user object's attending field. 

When a user marks an event attending, we also need to add this event to the user's GCal.

## Implementation

Look into Firebase's GCal integration and try to figure out how we can send the event object to the user's Google Calendar.

These changes will have to be made within the [markAttended()](https://github.com/Saakshaat/dequarantine/blob/master/backend/functions/handlers/events.js) function. Perhaps create a helper function and pass the event object to the helper function for interfacing the GCal API.

**Comment by littlezigy** [comment]
The events object needs to have a `start` object and an `end` object for start datetime and end datetime
