### ISSUE TITLE
Figure out how to do start/end date/time and what formats

### ISSUE THREAD

**Issue by Germain-L** [Saakshaat/dequarantine#36]
We need to figure out what time format to use,

I was thinking about converting every times entered into UTC time and store that in the backend, then the frontend would receive that and convert it in local timezone

In flutter i have a `DateTime` object available that's pretty simple to use, and the capability of doing what i described above

I don't know about react but i'm assuming this is doable as well.

What do we think?

**Comment by Germain-L** [comment]
So i've implemented it in the mobile app with something similar to that:
user enters a date and a time through a GUI, then is converted to UTC and ISO8601
```
//entered time by user  - YEAR, MONTH, DAY, HOUR, MINUTE
var inputTime = DateTime(2020, 04, 02, 14,36)
  //converts to UTC time zone and ISO8601
  .toUtc()
  .toIso8601String();

print(inputTime);
```
which prints `2020-04-02T13:36:00.000Z`

Hope that may help clear it up

**Comment by littlezigy** [comment]
> So i've implemented it in the mobile app with something similar to that:
> user enters a date and a time through a GUI, then is converted to UTC and ISO8601
> 
> ```
> //entered time by user  - YEAR, MONTH, DAY, HOUR, MINUTE
> var inputTime = DateTime(2020, 04, 02, 14,36)
>   //converts to UTC time zone and ISO8601
>   .toUtc()
>   .toIso8601String();
> 
> print(inputTime);
> ```
> 
> which prints `2020-04-02T13:36:00.000Z`
> 
> Hope that may help clear it up


This format works well with Google Cal too.
