### ISSUE TITLE
Add More Sections

### ISSUE THREAD

**Issue by Saakshaat** [Saakshaat/dequarantine#7]
@Germain-L 's Flutter test app is the basic idea of how we're planning on developing the frontend.

So far, we have a basic application where the main window/page has a gridview of cards with the event details. We want to organize our application so that the user can filter the events and only see cards for a certain criteria. 

We need to add more sections or tabs. When the user swipes to or selects a particular section, they should only see event cards for that.

The backend team will create filters in the API so that the frontend team needs to simply interface it as usual when the user turns to that section.

## Sections

Consider adding the following sections (or tabs):

- #### Attending 
   Any event that the user considers attending, they mark it as attending. These events end up in the attending section for that particular user account. 

  The backend team could also consider adding push notifications for whenever an 'attending' event is due. @sahil211999 we can think about how we want to implement this.

- #### Attended Events
  All the past events that a user has attended.

- #### Weekly Schedule
  This is the main window/page where the user can see all the events (basis their preference) occurring throughout the week.

- #### Categories
  This section has cards/sub-sections for all the different categories of events. Once the user selects a particular category, they only see cards tagged with that category. 

  Categories could be anything from Online Meetup to Watchparties to Online Classes.

- #### User Account
  One of the most important sections.

  This is where the user can access all their account information. Any basic app template would work here.

**Comment by Germain-L** [comment]
How about having a tab displaying currently live events and available to join, this would be a great feature for someone bored.

Could be done by displaying current events, with start and elapsed time
