### ISSUE TITLE
Firebase Database Modelling

### ISSUE THREAD

**Issue by Saakshaat** [Saakshaat/dequarantine#8]
We need to think about how we want to model our database on Firebase.

The frontend team needs to list what components they want the application to have in terms of the data they pull from the Firebase DB or interface from the APIs.

The backend team needs to decide how to model those requirements, given the cost and constraints of the read and write operations in Google Firebase.

List down your inputs in the comments.

**Comment by chadgainor** [comment]
Event name
Event image
Event category
Start time
Link to join event
Maximum # of attendees
Geotag of event?

**Comment by Germain-L** [comment]
I was thinking a list of tags along with a main category, that way users would be able to combine tags together for a more filtered view

**Comment by Saakshaat** [comment]
@Germain-L what kind of tags are you thinking about?
Could you describe it a little more?

What data would these tags need and hold?

**Comment by Germain-L** [comment]
@Saakshaat 

I was thinking tags such as
- type ( party, talk, workshop, competition ... )
- platform ( discord, twitch, zoom )
- category ( entertainment, programming, educational... )

examples:
- ReactJS workshop:
 - twitch
 - programming
 - educational
 - workshop

- Forest Gump watchparty
 - party
 - netflix
 - entertainment

**Comment by Saakshaat** [comment]
> @Saakshaat
> 
> I was thinking tags such as
> 
> * type ( party, talk, workshop, competition ... )
> * platform ( discord, twitch, zoom )
> * category ( entertainment, programming, educational... )
> 
> examples:
> 
> ReactJS workshop:
> 
> * twitch
> * programming
> * educational
> * workshop
> 
> Forest Gump watchparty
> 
> * party
> * netflix
> * entertainment

That's really interesting. Let's implement this in the second sprint.
